name: Testes Mutantes

on:
  # Runs on pushes targeting any branch other than "pages"
  push:
    branches-ignore: ["pages"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'
        cache-dependecy-path: '**/requirements*.txt'

    - name: Install dependecies
      run: |
        python --version
        pip --version
        echo Instalando dependencias
        cd app
        python -m pip install -r requirements.txt
        pip install mutmut
        pip install junit2html
        pip install requests

    - name: Run testes mutantes
      continue-on-error: true
      run: |
        echo iniciando testes
        if python -m mutmut run --paths-to-mutate app/calculadora --tests-dir app/tests --simple-output; then
          echo sucesso
        else
          echo erro
        fi
        echo fim

    - name: Run reports
      continue-on-error: true
      run: |
        echo gerando report html
        python -m mutmut html
        rm -rf html_reports/mutmut
        mkdir -p html_reports/mutmut
        mv html html_reports/mutmut
        echo gerando report xml
        python -m mutmut junitxml > html_reports/mutmut/mutmut-results.xml
        rm .mutmut-cache
        echo finalizando relatorio

    - name: Calcular score de mutantes
      run: |
        mkdir -p html_reports/badges
        if python .github/workflows/scripts/mutmut_score.py > /dev/null; then
            python ./.github/workflows/scripts/create_badge.py --text mutmut-score --value `python .github/workflows/scripts/mutmut_score.py` --color blue --file_name ./html_reports/badges/mutmut_score_badge.svg
        else
            python ./.github/workflows/scripts/create_badge.py --text mutmut-score --value error --color blue --file_name ./html_reports/badges/mutmut_score_badge.svg
        fi

    # - name: Commit changes
    #   run: |
    #     echo current repository
    #     echo ${{ github.repository }}
    #     git config --global user.email "no-reply@github.com"
    #     git config --global user.name "GitHub Actions"
    #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    #     git pull
    #     git add html_reports/mutmut
    #     git add html_reports/badges/mutmut_score_badge.svg
    #     git commit -m "update mutmut report"
    #     git push
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Configure Github Artifacts Path
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: report
    #     path: app/html
