name: Unit Tests Report

on:
  # Runs on pushes targeting any branch other than "pages"
  push:
    branches-ignore: ["pages"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'
        cache-dependency-path: '**/requirements*.txt'
        
    - name: Install dependencies
      run: |
        python --version
        pip --version
        echo Instalando dependencias
        cd app
        python -m pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pip install pytest-html
        pip install requests

    - name: Delete previous report
      run: |
        rm -rf html_reports/unit_test

    - name: Generate coverage report
      continue-on-error: true
      run: |
        if python -m pytest ./app/tests --cov-report html:html_reports/unit_test --cov-report xml:html_reports/unit_test/cov.xml --cov=./app/calculadora -vv; then
          echo "enriquecendo relatório de cobertura com output do pytest"
          echo "<hr><pre style='font-size: small; padding: 1em'>" >> html_reports/unit_test/index.html
          python -m pytest ./app/tests --cov-report term-missing --cov=./app/calculadora -vv >> html_reports/unit_test/index.html
          echo "</pre>" >> html_reports/unit_test/index.html
        else
          echo "testes unitários falharam"
        fi

    - name: Add unit test run badge
      run: |
        mkdir -p html_reports/badges
        if python -m pytest ./app/tests > /dev/null; then
            python ./html_reports/scripts/create_badge.py --text unit-tests --value passing --color green --file_name ./html_reports/badges/unit_tests_run_badge.svg
        else
            python ./html_reports/scripts/create_badge.py --text unit-tests --value not-passing --color red --file_name ./html_reports/badges/unit_tests_run_badge.svg
        fi

    - name: Add unit test coverage badge
      run: |
        mkdir -p html_reports/badges
        python ./html_reports/scripts/create_badge.py --text coverage --value `python html_reports/scripts/get_coverage.py` --color orange --file_name ./html_reports/badges/unit_tests_coverage_badge.svg

    - name: Create clear globs file
      run: |
        printf 'html_reports/**/*\n!.git'> .clear-target-files
        echo "$GITHUB_REF"
        echo "$env.GITHUB_REF"
        echo "${{ env.GITHUB_REF }}"
        echo "$GITHUB_REF_NAME"
        echo "$env.GITHUB_REF_NAME"
        echo "${{ env.GITHUB_REF_NAME }}"

    # Deploy to pages branch
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: pages
        FOLDER: html_reports
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAR_GLOBS_FILE: ".clear-target-files"
        TARGET_DIR: ${{ GITHUB_REF }}

    # - name: Commit changes
    #   run: |
    #     git config --global user.email "no-reply@github.com"
    #     git config --global user.name "GitHub Actions"
    #     rm html_reports/unit_test/.gitignore 
    #     git add html_reports/
    #     git commit -m "update coverage report"
    #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    #     git push
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
