name: Unit Tests Report

on:
  # Runs on pushes targeting any branch other than "pages"
  push:
    branches-ignore: ["pages"]

env:
  FOO: BAR
  VAR1: $GITHUB_REF_NAME
  VAR2: "$GITHUB_REF_NAME"
  VAR3: $env.GITHUB_REF_NAME
  VAR4: "$env.GITHUB_REF_NAME"
  VAR5: ${{ env.GITHUB_REF_NAME }}
  VAR6: "${{ env.GITHUB_REF_NAME }}"
  VAR7: ${{ github.repository }}
  VAR8: "${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'
        cache-dependency-path: '**/requirements*.txt'
        
    - name: Install dependencies
      run: |
        python --version
        pip --version
        echo Instalando dependencias
        cd app
        python -m pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pip install pytest-html
        pip install requests

    - name: Delete previous report
      run: |
        rm -rf html_reports/unit_test

    - name: Generate coverage report
      continue-on-error: true
      run: |
        if python -m pytest ./app/tests --cov-report html:html_reports/unit_test --cov-report xml:html_reports/unit_test/cov.xml --cov=./app/calculadora -vv; then
          echo "enriquecendo relatório de cobertura com output do pytest"
          echo "<hr><pre style='font-size: small; padding: 1em'>" >> html_reports/unit_test/index.html
          python -m pytest ./app/tests --cov-report term-missing --cov=./app/calculadora -vv >> html_reports/unit_test/index.html
          echo "</pre>" >> html_reports/unit_test/index.html
        else
          echo "testes unitários falharam"
        fi

    - name: Add unit test run badge
      run: |
        mkdir -p html_reports/badges
        if python -m pytest ./app/tests > /dev/null; then
            python ./html_reports/scripts/create_badge.py --text unit-tests --value passing --color green --file_name ./html_reports/badges/unit_tests_run_badge.svg
        else
            python ./html_reports/scripts/create_badge.py --text unit-tests --value not-passing --color red --file_name ./html_reports/badges/unit_tests_run_badge.svg
        fi

    - name: Add unit test coverage badge
      run: |
        mkdir -p html_reports/badges
        python ./html_reports/scripts/create_badge.py --text coverage --value `python html_reports/scripts/get_coverage.py` --color orange --file_name ./html_reports/badges/unit_tests_coverage_badge.svg

    - name: Print env vars
      run: |
        echo "FOO:"
        echo "$FOO"
        echo "1:"
        echo "$VAR1"
        echo "2:"
        echo "$VAR2"
        echo "3:"
        echo "$VAR3"
        echo "4:"
        echo "$VAR4"
        echo "5:"
        echo "$VAR5"
        echo "6:"
        echo "$VAR6"
        echo "7:"
        echo "$VAR7"
        echo "8:"
        echo "$VAR8"
        echo "-----"
        echo "FOO:"
        echo "$FOO"
        echo "local_1:"
        echo "$LOCAL1"
        echo "local_2:"
        echo "$LOCAL2"
        echo "local_3:"
        echo "$LOCAL3"
        echo "local_4:"
        echo "$LOCAL4"
        echo "local_5:"
        echo "$LOCAL5"
        echo "local_6:"
        echo "$LOCAL6"
        echo "local_7:"
        echo "$LOCAL7"
        echo "local_8:"
        echo "$LOCAL8"
      env:
        LOCAL_FOO: LOCAL_BAR 
        LOCAL1: $GITHUB_REF_NAME
        LOCAL2: "$GITHUB_REF_NAME"
        LOCAL3: $env.GITHUB_REF_NAME
        LOCAL4: "$env.GITHUB_REF_NAME"
        LOCAL5: ${{ env.GITHUB_REF_NAME }}
        LOCAL6: "${{ env.GITHUB_REF_NAME }}"
        LOCAL7: ${{ github.repository }}
        LOCAL8: "${{ github.repository }}"

    # Deploy to pages branch
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: pages
        FOLDER: html_reports
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIR: ${{ github.repository }}

    # - name: Commit changes
    #   run: |
    #     git config --global user.email "no-reply@github.com"
    #     git config --global user.name "GitHub Actions"
    #     rm html_reports/unit_test/.gitignore 
    #     git add html_reports/
    #     git commit -m "update coverage report"
    #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    #     git push
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
