name: Executar Testes Unitários
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
          
      - name: Install dependencies
        run: |
          python --version
          pip --version
          echo Instalando dependencias
          cd app
          python -m pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov
          pip install pytest-html
          
      - name: Run testes unitários
        run: |
          cd app
          python -m pytest --cov-report term-missing --cov=./calculadora -vv